### ISSUE TITLE
Assets missing?

### ISSUE THREAD

**Issue by midzer** [Astropilot/Bomberman#1]
Hi,

after compiling the game, it doesnt start because assets are missing.

Is it me, or are they not in the repo?

Have a nice weekend,
midzer

**Comment by Astropilot** [comment]
Hello!

It's strange because the assets are well included in the [build](https://github.com/Astropilot/Bomberman/tree/master/build) folder.
Normally the executable generated after compilation should be in the build folder too.
It's possible that you have to run it from the build folder and not from its parent folder to be sure that the executable finds the paths to the assets:
```console
$ cd build/
$ ./bomberman
```

**Comment by midzer** [comment]
Ooops, sorry. I didnt take a closer look in the `build` folder. THX!
